---
url: "https://www.CameronDugan.com"

# SEO Stuff
author: Cameron Dugan
description: This is my personal static website/portfolio/blog
lang: en
locale: en_US
# baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-sitemap

# RSS feeds
feed:
  posts_limit: 10000

