---
url: "https://www.CameronDugan.com"

author: Cameron Dugan
description: This a work portfolio and a blog about computers.
lang: en
locale: en_US

# markdown: kramdown
#
# kramdown:
#   syntax_highlighter: coderay

plugins:
  - jekyll-feed
  - jekyll-loading-lazy
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-minifier

# RSS feeds
feed:
  posts_limit: 10000

# minifier
jekyll-minifier:
  uglifier_args:
    harmony: true
  exclude: '*.p8'
  compress_json: false
