---
url: "https://www.CameronDugan.com"

author: Cameron Dugan
description: This a work portfolio and a blog about computers.
lang: en
locale: en_US

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap

# RSS feeds
feed:
  posts_limit: 10000
