plugins:
  - jekyll-feed
  - jekyll-sitemap

# SEO Stuff
author: Cameron Dugan
description: This is my Jekyll website that is running Simple.css
lang: en
locale: en_US
url: "https://www.camerondugan.com"
baseurl: ""

# RSS feeds
feed:
  posts_limit: 30
